version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - chmod +x gradlew
      - ./gradlew bootJar
artifacts:
  files:
    - build/libs/HospitalBackendSystem-0.0.1-SNAPSHOT.jar
#    - appspec.yml
  discard-paths: yes